### ISSUE TITLE
Code blocks to :code stack

### ISSUE THREAD

**Issue by Vaguery** [Vaguery/klapaucius#172]
Consider a new interpreter mode (off by default) in which every `:code` block that is "unwrapped" and pushed back onto `:exec` is also pushed to the `:code` stack at the same time.

**Comment by lspector** [comment]
Love this idea. Can't remember if you have tags or something similar, but tagging (or similar) on unwrapping also seems potentially interesting.

**Comment by Vaguery** [comment]
I don't have tags in the sense you originally described them. There is a `:tagspace` type, which is a data structure with sorted keys that are looked up with approximation. Open an issue to add tags as such! It will probably be feasible in the first post-integer release.

**Comment by Vaguery** [comment]
One problem here will be the (new) possibility of loops from the many instructions that push continuation code blocks to `:exec`. One would have to expect the `:code` stack to fill up with counter chaff.

**Comment by lspector** [comment]
Ooo... yes, maybe a guaranteed exponential explosion here...

**Comment by Vaguery** [comment]
/shrug I check for all instructions anyway

**Comment by Vaguery** [comment]
Consolidated by "promiscuous routing" in #175
