### ISSUE TITLE
Document environment stack

### ISSUE THREAD

**Issue by saulshanabrook** [Vaguery/klapaucius#49]
I am unclear what the `environment` stack is for and how it is used. It is core to the interpreter logic, [having something to do with filling up the exec stack](https://github.com/Vaguery/klapaucius/blob/6180021682517ac9ee9d81c5c72e5f99acb0718f/src/push/interpreter/core.clj#L340-L354). 

I think it would make sense to document the purpose of this stack and how it should be used.

**Comment by lspector** [comment]
This *should* help: https://push-language.hampshire.edu/t/environments/93

**Comment by Vaguery** [comment]
Yes, but this is a good point for completely containing a good Push description.

I'm writing a book about the language at the moment, so that will also help (and be included as part of the project site).

**Comment by Vaguery** [comment]
Will do after changing to `:snapshot` type

**Comment by Vaguery** [comment]
replaced with #105
