### ISSUE TITLE
disable-instruction function

### ISSUE THREAD

**Issue by Vaguery** [Vaguery/klapaucius#53]
simple way to disable a single instruction, for example `:float-sine` and `:float-cosine` when evolving symbolic regression fits to $y=sin(x)$

**Comment by lspector** [comment]
Not sure if this would go better in the issue re: random instructions, but many applications call for disabling all random instructions and it'd be good to have a simple way to do that.

**Comment by Vaguery** [comment]
My plan is to have the `one-with-everything` interpreter be the default configuration, but even that doesn't actually have _everything_ enabled. It will lack

- random variable sampling instructions (`:integer-uniform`, `:integer-binomial`, `:float-uniform`, `:boolean-coinflip` etc)
- plane geometry primitives from demos
- stuff that has been added in any of the other demos

I think the ideal default order will be:

- try to use `one-with-everything` as a starting template, adding new domain-specific functionality to that
- if you must limit the instruction set severely (because you are trying to evolve something that is explicitly or trivially solvable with the instructions themselves), construct a new template interpreter of your own; a good example is @nicmcphee's favorite of evolving arithmetic approximations to sine(x)
- disabling individual instructions _in the course of a run_ is intended as a tool for fine-tuning active searches: the equivalent of "whapping the side of the TV" to get a search past an attractive nuisance of a local solution

**Comment by Vaguery** [comment]
Also, the stress-testing acceptance tests use a `loaded-with-extras` interpreter template, that starts from `one-with-everything` and then adds all the extra crap from everywhere I can find a definition. I suspect sometime soon I'll actually write a programmatic thing that scours the project folder for instruction definitions.

**Comment by Vaguery** [comment]
Done in f406d64
