### ISSUE TITLE
implement `:ref` infrastructure

### ISSUE THREAD

**Issue by Vaguery** [Vaguery/klapaucius#54]

**Comment by Vaguery** [comment]
Various work in progress. Still needs:

- `:push-unbindall` forgets all bindings, including keys
- `:ref-unbind` forget a single binding
- `:x-similar` return a `:set` of `:ref` keys which currently hold items of the same type (at their tops)
- `:x-reverselookup`returns the a `:set` of `:ref` keys holding the value popped

**Comment by Vaguery** [comment]
Added 

- `:ref-clear` clears a binding's stack
- `:ref-forget` eliminates a binding completely

**Comment by Vaguery** [comment]
Noted: `PushDSL` command `replace-binding` can (potentially) be used to apply combinators to binding stacks.

**Comment by lspector** [comment]
Combinators on the binding stacks sounds interesting, though I'm not entirely sure I know what it means.

**Comment by Vaguery** [comment]
@lspector:

Still finishing up the docs, but the simple version is that instead of `:inputs` (Clojush) and/or `:names` (Push 3) there is just a single core abstraction in the Klapaucius interpreter for local on-demand storage: `:bindings`.

When used like Clojush `inputs`, arbitrary values can be bound to keyword keys in the interpreter when it's constructed or reset. So for example the call `(push.core/interpreter :bindings {:x1 12 :x2 false})` creates two bindings in the resulting interpreter, with keys `:x1` and `:x2`.

When the interpreter encounters a Clojure keyword on the `:exec` stack, it determines whether it's a key in the `:bindings` table, and if so it replaces it with its current bound value. As with Push 3 `name` items, there are instructions that can construct new `:ref` items, create new bindings, and so forth. Any type or module can be given the `storable` aspect, which constructs the type-specific instructions for storing and retrieving that type in `:bindings`, like `:foo-save` (which saves the top `:foo` item in the binding referenced by the top `:ref` item) and `:foo-store` (which saves the top `:foo` item in a brand new `:ref`).

So far so good?

The trick is: `:bindings` are not simple variables, but _stacks_. When an item is "saved" to a `:binding`, it is pushed onto an associated stack. The default behavior is not visibly different from that of Push 3 `name` items, but there's a lot more possibility with additional instructions that have added. So for example:

- `:quote-refs` changes interpreter behavior so all "registered" `:bindings` keys are pushed to `:ref` instead of being replaced with their bound values
- `:ref-clear` empties the stack associated with a `:ref` in the `:bindings` table
- `:ref-dump` copies the entire stack associated with a `:ref` onto the `:exec` stack, as a single code block
- `:ref-forget` removes a `:ref` from the `:bindings` table entirely, both key and values
- `:ref-fullquote` copies the entire stack associated with a `:ref` onto the `:code` stack, as a single code block
- `:ref-lookup` copies the top item from a `:binding` (it's "current value")
- `:ref-new` creates a unique new `:ref` and pushes it to the `:ref` stack
- `:unquote-refs` turns back on the interpreter's ability to look up `:ref` keys in the `:bindings` table

and some tricks from the `storable` aspect:

- `:x-savestack` creates a copy of the `:x` stack in the `:bindings` table using a given `:ref`
- `:x-storestack` creates a copy of the `:x` stack in the `:bindings` table using a new unique `:ref`

So far so good?

"Combinators on the binding stacks" implies things like `:binding-dup`, `:binding-rot`, `:binding-cutflip` and so forth. That is, all the combinators that apply to the standard interpreter stacks can be applied to the _ad hoc_ `:bindings` stacks as well.

Simple :smile:

**Comment by lspector** [comment]
A lot of this is indeed clear and seems like a good abstraction for names, inputs, and maybe more.

I'm not entirely clear about how `:ref`s are manipulated or about what the implications of all of this are for the minimum lengths of programs that use these mechanisms... I think I would understand this best from a few simple examples. 

The possibility of meta-programming binding usage (is that a fair description) does sound cool, but whether or not it will help or hinder our long-running quest to make nameish things evolvable is also not clear to me.

Which brings me to one more question: Can this abstraction also handle something approximating tags, for which matching can be inexact (so that all references refer to something)?

**Comment by Vaguery** [comment]
I am considering that now. The plan for the 1.2 release includes:

- `:ref` and `:binding` infrastructure to store and manipulate inputs, outputs and local variables
- first-class functions and higher-order functions
- a `map` abstraction
- fixing the numerics type system so it isn't dependent on the implementation language, and can be expanded

**Comment by Vaguery** [comment]
@lspector 

> Which brings me to one more question: Can this abstraction also handle something approximating tags, for which matching can be inexact (so that all references refer to something)?

I think the interesting issue there is whether the abstraction to a tag-space storage model for "just bindings" will "seep out" and want to change how we think of stacks and instructions more broadly.

**Comment by lspector** [comment]
"Tag Space Machines" (https://push-language.hampshire.edu/t/tag-space-machines/246) can be viewed as an approach embracing maximal seepage.

**Comment by Vaguery** [comment]
Yes. As I said in that thread, I have a sense that the `:ref`/`:binding` architecture in some sense "furthers" the "stackiness" of Push—it somehow echoes the fundamental architecture of the stack-based dynamics.

I'm not ruling it out, but I want to consider carefully whether a program in the "Tag language" is fundamentally a Push program with tags slapped on, or a tag-driven language at its core.

My hesitation comes from the work I've done on the `ReQ` language: the fundamental abstraction there is the _queue_ instead of the _stack_, and as a result a whole slew of interesting but incommensurate architectural changes have followed. `ReQ` can't be Push because something deep changed when I shifted from stacks to queues. In the same way, I think I would rather make a tag-driven language into a language as such.

**Comment by Vaguery** [comment]
Might want to add some additional instructions as they become apparent, but otherwise working as designed. `:ref` values are routed correctly, looked up, the `:binding` values are stacks themselves, and various introspection instructions support this. Still to do (but already another Issue) is making bindings have combinators of their own.
