### ISSUE TITLE
Get or write or evolve a better :string->scalar function

### ISSUE THREAD

**Issue by Vaguery** [Vaguery/klapaucius#90]
Deleted the old `:string->integer` and `:string->float` instructions, because they're essentially bullshit.

Good overall acceptance test for evolutionary search: evolve a number-parser.

**Comment by lspector** [comment]
By that logic, everything but `nand` is essentially bullshit.

**Comment by Vaguery** [comment]
Might do better.

https://github.com/Vaguery/klapaucius/blob/master/test/push/instructions/base/integer_test.clj#L362-L382

**Comment by Vaguery** [comment]
Done as https://github.com/Vaguery/klapaucius/blob/376a03865837b2a9d0de43e8f088ac0de977173b/src/push/type/item/string.clj#L70-L79
